---
ntp:
  - server_ip: 1.1.1.1
    src_iface: 2.2.2.2
  - server_ip: 10.10.10.10
    src_iface: 

info_center:
    server_ip: 1.1.1.1,2.2.2.2
    src_iface: 

static_route:
  - dest: 10.0.0.0/8
    out_iface:
    nexthop: 12.1.1.2
    desc: test-route
  - dest: 123.0.0.5/29
    out_iface: S0/1/0
    nexthop: 13.2.2.1
    desc:

l2_interface:
  # iface_name :g1/0/[1-10]  will be g1/0/1,g1/0/2,...g1/0/10
  - iface_name: g1/0/[1-10]
    desc: 13213
    link_type: access
    allow_vlan: 10
  - iface_name: g1/0/[48]
    desc: 
    link_type: trunk
    allow_vlan: 10 20 30

l3_interface:
  - iface_name: loop0
    desc: test
  # ipaddr example: 172.16.1.1/24
    ipaddr: 192.168.255.1/32
  - iface_name: g0/0
    desc:
    ipaddr: 12.1.0.1/30

vlan:
# key 'id' must be a string separated by ',', 'name' is optional.
  - id: '10'
    name: pr
  - id: '20'
    name: ts
  - id: 10,20,30
    name:

bagg:
  - number: 10
    desc: 132
    link_type: trunk
    allow_vlan: 10 20 30 40
    lacp_mode: dynamic
    member: g0/0,g0/1,g0/2
  - number: 20
    desc: 
    link_type: access
    allow_vlan: 10
    lacp_mode: static
    member: g1/0,g1/1,g1/2
